# Generated by Django 4.2.5 on 2023-09-23 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zip_code',
            new_name='pin_code',
        ),
    ]
